### ISSUE TITLE
Is it finished and working ?

### ISSUE THREAD

**Issue by david-soyez** [star-scraper/apollo-link-jwt#4]
I have implemented the module in my app: when i refresh the page, accessToken is gone but there is a refreshToken (so far so good), then there is a query in my app that returns an UNAUTHENTICATED but then nothing happens. It should trigger the mutation to get a refreshed token but it doesn't happen.
Is this finished ?
This is where it happens, it forwards the same query again without doing a refresh token. 
https://github.com/star-scraper/apollo-link-jwt/blob/379f0fdfe397e470dcca6554b17192d77e180cd8/lib/index.js#L148

**Comment by star-scraper** [comment]
Good point and thanks for pointing this out!  I've been using this primarily for mobile, so I persist the access token in Async Storage but I didn't think of that possible use case, do you mind opening up a PR against the repo and I'll approve and merge it? Much appreciated @david-soyez

**Comment by david-soyez** [comment]
oh ok, it makes sense on mobile.
I'm working on this today again I wasn't done yesterday, so I will test more and then do a PR.
Thanks for your answer.

**Comment by david-xocial** [comment]
I have created a PR. Everything seems to work fine for me.
The only thing I had to to add is that on the first page load both tokens don't exist and a graphql query returns UNAUTHENTICATED which is not handle by this module, meaning it does a forward(operation) and causes a query to be called twice. To avoid that I had to add a condition in my app to redirect to /login when the refresh token doesn't exist.
It would be nice to add a note in the README to say that the user must handle the check authenticated themselves when the app first loads.

**Comment by david-xocial** [comment]
Following my previous post, I was thinking you could add a failedAuth function in the parameter that would be called when a auth fails, (which is different than onRefreshComplete) it would be called whenever a query returns a UNAUTH..

**Comment by star-scraper** [comment]
Sure thing, I'll take a look at adding that change this evening.  I look forward to the PR as well, thanks for your help @david-soyez!

**Comment by david-soyez** [comment]
I'm going to add a onAuthenticated function to the settings.
It will be called before queries when the refresh token has expired or when a query returns unauthenticated.

Why, because i noticed that when the refresh token is expired, nothing happens, (same case as my previous post) the refreshTokens function isn't called (because the refresh token is expired) and then it does the forward(operation) that fails because we're not unauthenticated.

So the idea is that the onAuthenticated function will help to catch unauthenticated actions so that we can redirect to the login page.

So the two cases are:
- When there is a query, if refresh token is expired: onAuthenticated is trigger (and we redirect to login page in our app)
- When there is a query, refresh token is valid but for some reasons the server respond unauthenticated: onAuthenticated is trigger (and we redirect to login page in our app)

**Comment by david-soyez** [comment]
Sorry just deleting comments, i have to try things before.

**Comment by star-scraper** [comment]
Here's an example of how one my apps uses the 'onRefreshComplete' to see if the response was valid which can be any shape and then checked manually:

`  const onRefreshComplete = async (data) => {
    /**
     * Find and return the access token and refresh token from the provided fetch callback
     */
    const newAccessToken = data?.data?.token?.accessToken;
    const newRefreshToken = data?.data?.token?.refreshToken;

    /**
     * Handle sign out logic if the refresh token attempt failed
     */
    if (!newAccessToken || !newRefreshToken) {
      console.log('Redirect back to login, because the refresh token was expired!');

      await signOutHandler();

      return;
    }

    // Update tokens in AsyncStorage
    await setAsyncStorage(ACCESS_TOKEN, newAccessToken);
    await setAsyncStorage(REFRESH_TOKEN, newRefreshToken);

    // Return the tokens back to the lib to cache for later use
    return {
      newAccessToken,
      newRefreshToken,
    };
  };`

**Comment by david-xocial** [comment]
I'm going to try if if makes more sense that the app should catch the unauthenticated error with apolloError.
I wanted to skip the unauthenticated query when the refresh token is expired but then i thought maybe it's a public query and we should rather leave it and the app will catch the unauthenticated error itself.

**Comment by david-xocial** [comment]
I create a PR with a small change only.
I tried a few things but i will handle it from my app directly. I don't want to break the current status of the repo especially if there people using it in actives projects.
